# A first workflow to play around with the editor
name: My First Workflow
on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name: Greet the user
        run: |
          echo "Hello ${{ vars.WHO_TO_GREET }}, from ${{ github.actor }}!"
          echo 'My secret is ${{ secrets.MY_SECRET }}'
          echo "Current branch is ${{ github.ref }}"
        shell: bash
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - run: tree
  test:
    runs-on: ubuntu-latest
    environment: Test
    needs: [first_job]
    steps:
      - run: |
          echo "Hello ${{ vars.WHO_TO_GREET }}, from ${{ github.actor }}"
          sec $(${{ secrets.MY_SECRET }}|sed 's/./%/g')
          echo 'My secret is $sec'
          echo 'Current branch is ${{ github.ref }}          
  load-test:
    runs-on: ubuntu-latest
    environment: Load-Test
    needs: [first_job]
    steps:
      - run: |
          echo 'Hello ${{ vars.WHO_TO_GREET }}, from ${{ github.actor }}'
          sec $(${{ secrets.MY_SECRET }}|sed 's/./%/g')
          echo 'My secret is $sec'
          echo 'Current branch is ${{ github.ref }}
  production:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://writeabout.net
    needs: [test, load-test]
    steps:
      - run: |
          echo 'Hello ${{ vars.WHO_TO_GREET }}, from ${{ github.actor }}'
          sec $(${{ secrets.MY_SECRET }}|sed 's/./%/g')
          echo 'My secret is $sec'
          echo 'Current branch is ${{ github.ref }}'
    
